name: potea_edu
description: "Aplicativo educacional Potea com design moderno e funcionalidades para alunos e professores"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de estado
  flutter_riverpod: ^2.4.9

  # UI e Design
  google_fonts: ^6.1.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9

  # Navegação
  go_router: ^12.1.3

  # Utilitários
  intl: ^0.19.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Animações
  lottie: ^2.7.0

  # Ícones
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
